spring:
  application:
    name: notification-service

  profiles:
    active: rabbitmq, postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000

  mongodb:
    uri: mongodb://admin:admin123@localhost:27017/notificationdb?authSource=admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecommerce.plateform.notificationservice.kafka.OrderEvent

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8082

jwt:
   secret: ${JWT_SECRET}
   expiration: 86400000